In [56]:
a = [1.0, 2.0, 1.0]
print(a)

[1.0, 2.0, 1.0]


In [57]:
a[0]

1.0

In [58]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [59]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [60]:
a[1]

tensor(1.)

In [61]:
float(a[1])

1.0

In [62]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [63]:
points = torch.zeros(6)
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0

points

tensor([1., 4., 2., 1., 3., 5.])

In [64]:
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
points

tensor([1., 4., 2., 1., 3., 5.])

In [65]:
float(points[0]), float(points[1])

(1.0, 4.0)

In [66]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [67]:
points.shape

torch.Size([3, 2])

In [68]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [69]:
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [70]:
points[0,1]

tensor(4.)

In [71]:
points[0]

tensor([1., 4.])

In [72]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [73]:
points_storage = points.storage()
points_storage[0]

1.0

In [74]:
points.storage()[1]

4.0

In [75]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])

In [76]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.storage_offset()

2

In [77]:
second_point.size()

torch.Size([2])

In [78]:
second_point.shape

torch.Size([2])

In [79]:
points.stride()

(2, 1)

In [80]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.size()

torch.Size([2])

In [81]:
second_point.storage_offset()

2

In [82]:
second_point.stride()

(1,)

In [83]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])

In [84]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [85]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [86]:
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [87]:
id(points.storage()) == id(points_t.storage())

True

In [88]:
points.stride()

(2, 1)

In [89]:
points_t.stride()

(1, 2)

In [90]:
some_tensor = torch.ones(3, 4, 5)
some_tensor_t = some_tensor.transpose(0, 2)
some_tensor.shape

torch.Size([3, 4, 5])

In [91]:
some_tensor_t.shape

torch.Size([5, 4, 3])

In [92]:
some_tensor.stride()

(20, 5, 1)

In [93]:
some_tensor_t.stride()

(1, 5, 20)

In [94]:
points.is_contiguous()

True

In [95]:
points_t.is_contiguous()

False

In [96]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [97]:
points_t.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [98]:
points_t.stride()

(1, 2)

In [99]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [100]:
points_t_cont.stride()

(3, 1)

In [101]:
points_t_cont.storage()

 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]

In [103]:
double_points = torch.ones(10, 2, dtype=torch.short)
short_points = torch.tensor([[1,2],[3,4]], dtype=torch.short)

In [104]:
short_points.dtype

torch.int16

In [105]:
double_points = torch.zeros(10,2).double()
short_points = torch.ones(10,2).short()

In [106]:
double_points = torch.zeros(10,2).to(torch.double)
short_points = torch.ones(10,2).to(dtype=torch.short)

In [107]:
points = torch.rand(10,2)
short_points = points.type(torch.short)

In [108]:
some_list = list(range(6))
some_list[:]


[0, 1, 2, 3, 4, 5]

In [109]:
some_list[1:4]

[1, 2, 3]

In [110]:
some_list[1:]

[1, 2, 3, 4, 5]

In [111]:
some_list[:4]

[0, 1, 2, 3]

In [112]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [113]:
some_list[1:4:2]

[1, 3]

In [114]:
points[1:]

tensor([[0.0940, 0.3620],
        [0.2538, 0.6263],
        [0.9273, 0.0219],
        [0.0291, 0.1072],
        [0.9147, 0.1500],
        [0.9413, 0.3563],
        [0.8300, 0.1759],
        [0.6496, 0.7718],
        [0.2727, 0.9917]])

In [115]:
points[1:, :]

tensor([[0.0940, 0.3620],
        [0.2538, 0.6263],
        [0.9273, 0.0219],
        [0.0291, 0.1072],
        [0.9147, 0.1500],
        [0.9413, 0.3563],
        [0.8300, 0.1759],
        [0.6496, 0.7718],
        [0.2727, 0.9917]])

In [116]:
points[1:, 0]

tensor([0.0940, 0.2538, 0.9273, 0.0291, 0.9147, 0.9413, 0.8300, 0.6496, 0.2727])

In [117]:
points[1:, 1]

tensor([0.3620, 0.6263, 0.0219, 0.1072, 0.1500, 0.3563, 0.1759, 0.7718, 0.9917])

In [118]:
points = torch.ones(3,4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [120]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])